# Robotics_01

### Виконав: Давидчук Артем, ІО-41

Варіант: 106

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from ipywidgets import interact, IntSlider, FloatSlider

L1 = 0.4
L2 = 0.4
L3 = 0.3
L4 = 0.1

theta1_g = 45
theta2_g = -30
theta3_g = -20
theta4_g = -15

def plot_segment4(theta1g, theta2g, theta3g, theta4g):

    # Перетворюємо кути в радіани
    theta1 = np.radians(theta1g)
    theta2 = np.radians(theta2g)
    theta3 = np.radians(theta3g)
    theta4 = np.radians(theta4g)

    # Розраховуємо координати суглобів (joints)
    x1, y1 = 0, 0
    x2 = x1 + L1 * np.cos(theta1)
    y2 = y1 + L1 * np.sin(theta1)
    x3 = x2 + L2 * np.cos(theta1 + theta2)
    y3 = y2 + L2 * np.sin(theta1 + theta2)
    x4 = x3 + L3 * np.cos(theta1 + theta2 + theta3)
    y4 = y3 + L3 * np.sin(theta1 + theta2 + theta3)
    x5 = x4 + L4 * np.cos(theta1 + theta2 + theta3 + theta4)
    y5 = y4 + L4 * np.sin(theta1 + theta2 + theta3 + theta4)

    fig, ax = plt.subplots(figsize=(14, 7))

    ax.grid(True)

    ax.set_xlabel('X')
    ax.set_ylabel('Y')

    # Рисуємо маніпулятор
    ax.plot([x1, x2], [y1, y2], 'b-', linewidth=8, label='L1')
    ax.plot([x2, x3], [y2, y3], 'g-', linewidth=5, label='L2')
    ax.plot([x3, x4], [y3, y4], 'r-', linewidth=4, label='L3')
    ax.plot([x4, x5], [y4, y5], 'k-', linewidth=2, label='L4')

    ax.plot(x1, y1, 'ro', markersize=9, label='joint 1')
    ax.plot(x2, y2, 'yo', markersize=9, label='joint 2')
    ax.plot(x3, y3, 'ko', markersize=9, label='joint 3')
    ax.plot(x4, y4, 'go', markersize=9, label='joint 4')
    ax.plot(x5, y5, 'rx', markersize=9, label='end effector')

    # Додаємо легенду
    ax.legend(loc='upper right')

    ax.set_xlim(-0.5, 1.5)
    ax.set_ylim(0, 1)
    ax.set_title(f'Four-link planar manipulator:\n Joint2 (x2={x2:.4f}, y2={y2:.4f}), Joint3 (x3={x3:.4f}, y3={y3:.4f}), Joint4 (x4={x4:.4f}, y4={y4:.4f}) \n end effector (x5={x5:.4f}, y5={y5:.4f}) ')
    plt.show()

#interact(plot_segment, length=IntSlider(min=1, max=10, step=1, value=5));
interact(plot_segment4,
     theta1g=IntSlider(value=theta1_g, min=-180, max=180, step=1, description='θ1:'),
     theta2g=IntSlider(value=theta2_g, min=-180, max=180, step=1, description='θ2:'),
     theta3g=IntSlider(value=theta3_g, min=-180, max=180, step=1, description='θ3:'),
     theta4g=IntSlider(value=theta4_g, min=-180, max=180, step=1, description='θ4:'))


interactive(children=(IntSlider(value=42, description='θ1:', max=180, min=-180), IntSlider(value=-26, descript…

<function __main__.plot_segment4(theta1g, theta2g, theta3g, theta4g)>

In [7]:
def T(theta, d_x, d_y):
    """
    Створює матрицю перетворення систем координат для 2D.
    Parameters:
        theta (float): Кут повороту в радіанах
        d_x (float): Зміщення системи координат по осі X
        d_y (float): Зміщення системи координат по осі Y

    Returns:
        numpy.ndarray: Матриця перетворення T [3x3]
    """
    return np.array([
        [np.cos(theta), -np.sin(theta), d_x],
        [np.sin(theta),  np.cos(theta), d_y],
        [0,              0,             1]
    ])

theta1 = np.radians(theta1_g)
theta2 = np.radians(theta2_g)
theta3 = np.radians(theta3_g)
theta4 = np.radians(theta4_g)

T1 = T(theta1,0, 0)
T2 = T(theta2,L1,0)
T3 = T(theta3,L2,0)
T4 = T(theta4,L3,0)

joint2 = T1 @           np.array([[L1], [0], [1]])
joint3 = T1 @ T2 @      np.array([[L2], [0], [1]])
joint4 = T1 @ T2 @ T3 @ np.array([[L3], [0], [1]])

print('\njoint2_fixed_frame [x2; y2; 1]')
print(joint2)

print('\njoint3_fixed_frame [x3; y3; 1]')
print(joint3)

print('\njoint4_fixed_frame [x4; y4; 1]')
print(joint4)

T = T1 @ T2 @ T3 @ T4

end_effector_mooving_frame4 = np.array([[L4], [0], [1]])
end_effector_fixed_frame = T @ end_effector_mooving_frame4

print('\nend_effector_fixed_frame [x5; y5; 1]')
print(end_effector_fixed_frame)

print('\nTransformation matrix T з системи координат Mooving Frame 4 в Fixed Frame \n')
print('T=')
print(T)



joint2_fixed_frame [x2; y2; 1]
[[0.37157241]
 [0.3345653 ]
 [1.        ]]

joint3_fixed_frame [x3; y3; 1]
[[0.75607709]
 [0.44482025]
 [1.        ]]

joint4_fixed_frame [x4; y4; 1]
[[0.95531603]
 [0.46225139]
 [1.        ]]

end_effector_fixed_frame [x5; y5; 1]
[[1.03520639]
 [0.45806452]
 [1.        ]]

Transformation matrix T з системи координат Mooving Frame 4 в Fixed Frame 

T=
[[ 0.99862953  0.05233596  0.95531603]
 [-0.05233596  0.99862953  0.46225139]
 [ 0.          0.          1.        ]]
